[package]
name = "enquo-core"
version = "0.0.0-git"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11.0"
ciborium = "0.2.0"
hmac = "0.12.0"
ore-rs = "0.3.0"
rand_chacha = "0.3.0"
serde = { version = "1.0.0", features = ["derive"] }
sha2 = "0.10.0"
thiserror = "1.0.0"
