[package]
name = "enquo"
version = "0.0.0"
edition = "2021"

[dependencies]
enquo-core = { path = "../../../rust" }
lazy_static = "1.0"
serde_json = "1.0"
rb-sys = "0.8"
rutie = { git = "https://github.com/mpalmer/rutie", branch = "fixes" }

[lib]
crate-type = ["cdylib"]
