[package]
name = "enquo"
version = "0.0.0"
edition = "2021"

[dependencies]
enquo-core = { path = "../../../rust" }
lazy_static = "1.0"
serde_json = "1.0"
magnus = "0.5"
hex = "0.4"

[lib]
crate-type = ["cdylib"]
