[package]
name = "enquo"
version = "0.0.0"
edition = "2021"

[dependencies]
enquo-core = { path = "../../../rust" }
lazy_static = "1.0.0"
serde_json = "1"
rb-sys = "0.8.0"
rutie = { git = "https://github.com/mpalmer/rutie", branch = "rb_sys" }

[lib]
crate-type = ["cdylib"]
