name: "Pre-merge Quality-Control: Rust"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"

    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.rustc_hash}}-cargo

      - name: Run testsuite
        working-directory: rust
        run: |
          cargo test

  qc:
    runs-on: ubuntu-latest
    name: "Quality Control"

    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        id: rust-install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.rustc_hash}}-cargo

      - name: Check formatting
        working-directory: rust
        run: |
          cargo fmt --check

      - name: Consult Clippy
        working-directory: rust
        run: |
          cargo clippy -- -D warnings
