name: "Pre-merge Quality-Control: Rust"
on:
  push:
    paths:
      - rust/**
      - .github/workflows/qc_rust.yml
  pull_request:
    branches: [main]
    paths:
      - rust/**
      - .github/workflows/qc_rust.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"

    strategy:
      matrix:
        rust-toolchain: ['stable', 'nightly']
      fail-fast: false

    env:
      RUST_ICU_MAJOR_VERSION_NUMBER: 70

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-cargo

      - name: Install build-deps
        run: sudo apt update && sudo apt install -y libicu-dev

      - name: Run testsuite
        working-directory: rust
        env:
          RUSTFLAGS: -D warnings
        run: |
          cargo +${{ steps.rust-install.outputs.name }} test
          cargo +${{ steps.rust-install.outputs.name }} test --features icu

  qc:
    runs-on: ubuntu-latest
    name: "Quality Control"

    env:
      RUST_ICU_MAJOR_VERSION_NUMBER: 72

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-cargo

      - name: Check formatting
        working-directory: rust
        run: |
          cargo fmt --check

      - name: Consult Clippy
        working-directory: rust
        run: |
          cargo +${{ steps.rust-install.outputs.name }} clippy -- -D warnings
          cargo +${{ steps.rust-install.outputs.name }} clippy --features icu -- -D warnings

      - name: Check docs
        working-directory: rust
        run: |
          cargo +${{ steps.rust-install.outputs.name }} rustdoc -- -D warnings
