name: "Pre-merge Quality-Control: Rust"
on:
  push:
    branches: [main]
    paths:
      - rust/**
      - .github/workflows/qc_rust.yml
  pull_request:
    branches: [main]
    paths:
      - rust/**
      - .github/workflows/qc_rust.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"

    env:
      RUST_ICU_MAJOR_VERSION_NUMBER: 70

    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.rustc_hash}}-cargo

      - name: Install build-deps
        run: sudo apt update && sudo apt install -y libicu-dev

      - name: Run testsuite
        working-directory: rust
        run: |
          cargo test

  qc:
    runs-on: ubuntu-latest
    name: "Quality Control"

    env:
      RUST_ICU_MAJOR_VERSION_NUMBER: 70

    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        id: rust-install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.rustc_hash}}-cargo

      - name: Install build-deps
        run: sudo apt update && sudo apt install -y libicu-dev

      - name: Check formatting
        working-directory: rust
        run: |
          cargo fmt --check

      - name: Consult Clippy
        working-directory: rust
        run: |
          cargo clippy -- -D clippy::dbg_macro -D warnings
