name: "Release to crates.io"
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    name: "Upload"

    env:
      RUST_ICU_MAJOR_VERSION_NUMBER: 70

    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-cargo

      - name: Set Cargo.toml version
        shell: bash
        working-directory: rust
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          mv Cargo.toml Cargo.toml.tmpl
          sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml.tmpl >Cargo.toml
          rm Cargo.toml.tmpl

      - name: Do The Needful
        working-directory: rust
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo publish --allow-dirty
